### ISSUE TITLE
Build fail: make en

### ISSUE THREAD

**Issue by loocars** [google/blockly-games#106]
I tried to build blockly-games like this page shows: https://github.com/google/blockly-games/wiki/Build

'make deps' worked perfectly fine

If I use 'make en', I get this error:

mkdir -p appengine/generated/en/
java -jar third-party/SoyToJsSrcCompiler.jar --shouldProvideRequireSoyNamespaces --isUsingIjData --outputPathFormat appengine/index/generated/en/soy.js --srcs appengine/index/template.soy
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$2 (file:/home/lukas/Dokumente/git/blockly-games/third-party/SoyToJsSrcCompiler.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
python build-app.py index en

Index - en - uncompressed:
Traceback (most recent call last):
  File "build-app.py", line 222, in <module>
    main(sys.argv[1], sys.argv[2])
  File "build-app.py", line 42, in main
    language(name, lang)
  File "build-app.py", line 71, in language
    write_uncompressed(name, lang)
  File "build-app.py", line 91, in write_uncompressed
    print("Failed to Popen: %s" & cmd)
TypeError: unsupported operand type(s) for &: 'str' and 'list'
Makefile:20: recipe for target 'index-en' failed
make: *** [index-en] Error 1

---------------------------------------------------------------------

Im using xUbuntu as OS on a Virtual Machine

Thank you for any responses

**Comment by NeilFraser** [comment]
Does `third-party/build/closurebuilder.py` exist in your directory after you run `make deps`?

**Comment by loocars** [comment]
No I only have these files in my third-party folder:
closure-compiler.jar                         compiler-latest.zip
closure-templates-for-javascript-latest.zip  SoyMsgExtractor.jar
closure-templates-msg-extractor-latest.zip   SoyToJsSrcCompiler.jar

Even the build folder is missing.

**Comment by NeilFraser** [comment]
Hmm, something went wrong right at the start of `make deps`.  Here's what I see on my console:

```
fraser-macbookpro2:blockly-games fraser$ make deps
mkdir -p third-party
cd third-party; \
	svn checkout https://github.com/google/closure-library/trunk/closure/bin/build build; \
	wget -N https://dl.google.com/closure-templates/closure-templates-for-javascript-latest.zip; \
	unzip -o closure-templates-for-javascript-latest.zip SoyToJsSrcCompiler.jar; \
	unzip -o closure-templates-for-javascript-latest.zip -d ../appengine/third-party soyutils_usegoog.js; \
	wget -N https://dl.google.com/closure-templates/closure-templates-msg-extractor-latest.zip; \
	unzip -o closure-templates-msg-extractor-latest.zip SoyMsgExtractor.jar; \
	wget -N https://dl.google.com/closure-compiler/compiler-latest.zip; \
	unzip -o compiler-latest.zip -x COPYING README.md; \
	mv -f closure-compiler-v*.jar closure-compiler.jar; \
	chmod +x build/closurebuilder.py
A    build/closurebuilder.py
A    build/depstree.py
A    build/depstree_test.py
A    build/depswriter.py
A    build/depswriter_test.py
A    build/jscompiler.py
A    build/jscompiler_test.py
A    build/source.py
A    build/source_test.py
A    build/treescan.py
Checked out revision 8154.
```
(...followed by pages and pages of other stuff loading...)

Is your system unable to execute that `svn checkout https://github.com/google/closure-library/trunk/closure/bin/build` command?
