### ISSUE TITLE
Cannot build pond-tutor or pond-duck

### ISSUE THREAD

**Issue by davidkmrcode** [google/blockly-games#129]
When I run make pond-tutor-en, I get the following:

./appengine/pond/tutor/generated/en/soy.js:13: ERROR - [JSC_MISSING_MODULE_OR_PROVIDE] Required namespace "Pond.soy" never defined.
goog.require('Pond.soy');
^^^^^^^^^^^^^^^^^^^^^^^^

./appengine/pond/tutor/js/tutor.js:30: ERROR - [JSC_MISSING_MODULE_OR_PROVIDE] Required namespace "Pond" never defined.
goog.require('Pond');
^^^^^^^^^^^^^^^^^^^^

./appengine/pond/tutor/js/tutor.js:31: ERROR - [JSC_MISSING_MODULE_OR_PROVIDE] Required namespace "Pond.Battle" never defined.
goog.require('Pond.Battle');
^^^^^^^^^^^^^^^^^^^^^^^^^^^

./appengine/pond/tutor/js/tutor.js:32: ERROR - [JSC_MISSING_MODULE_OR_PROVIDE] Required namespace "Pond.Blocks" never defined.
goog.require('Pond.Blocks');
^^^^^^^^^^^^^^^^^^^^^^^^^^^

./appengine/pond/tutor/js/tutor.js:34: ERROR - [JSC_MISSING_MODULE_OR_PROVIDE] Required namespace "Pond.Visualization" never defined.
goog.require('Pond.Visualization');
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Similar message when I run make pond-duck-en. I'm able to build everything else successfully. Please help.

**Comment by NeilFraser** [comment]
That doesn't sound good.  I'll look at this in about four hours (after my daughter's bedtime).

**Comment by NeilFraser** [comment]
I'm afraid I'm unable to recreate these errors.  Try updating your repo to the latest version, then `make clean`, then `make deps`, then `make pond-tutor-en` and see if the error is still there.

**Comment by davidkmrcode** [comment]
I pulled the latest, ran make clean, make deps, and make en again. Same result, everything built fine except pond-tutor and pond-duck. Same errors. I also saw the following before the pond-tutor error:

Compiling Pond/Docs - en
Exception in thread pond/docs:
Traceback (most recent call last):
  File "build-app.py", line 160, in run
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE)
  File "C:\Users\Dave\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Dave\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 is not a valid Win32 application

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dave\AppData\Local\Programs\Python\Python38-32\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "build-app.py", line 162, in run
    raise Exception("Failed to Popen: %s" % ' '.join(cmd))
Exception: Failed to Popen: third-party-downloads/build/closurebuilder.py --root=appengine/third-party/ --root=appengine/generated/en/ --root=appengine/js/ --namespace=Pond.Docs --output_mode=list --root=appengine/pond/docs/generated/en/ --root=appengine/pond/docs/js/
Compressed to 49 KB.

I'm doing this on Windows 10 from a VS Code terminal, is that a problem?

Also, in order for make deps to work, I had to add the following to the end of the four wgets in the make file:
--no-check-certificate

**Comment by NeilFraser** [comment]
Ah, Windows.  My bet is it's a path issue caused by '/' vs. '\\'.  Will look at it this evening.

**Comment by davidkmrcode** [comment]
I just pulled down the repo in an AWS Linux environment and ran make deps, and got the following error:

java -jar third-party-downloads/closure-compiler.jar\
 --language_out ECMASCRIPT5_STRICT\
 --js appengine/third-party/JS-Interpreter/acorn.js\
 --js appengine/third-party/JS-Interpreter/interpreter_.js\
 --js_output_file appengine/third-party/JS-Interpreter/compressed.js
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/google/javascript/jscomp/CommandLineRunner : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:808)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:443)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:65)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:349)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:348)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:430)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:323)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
make: *** [deps] Error 1

Any idea what that's about?

**Comment by NeilFraser** [comment]
That one appears to be this error:
https://github.com/google/closure-compiler/issues/3059
Closure Compiler needs a more recent version of Java?

**Comment by davidkmrcode** [comment]
Upgrading Java solved the problem, and I was able to make en on Linux with no errors. My main machine is Windows, so would be nice to get it to work on Windows, but it's okay if not. Thanks for helping me out.
