### ISSUE TITLE
build error: options.excludes: type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by Baloneo** [google/blockly-games#204]
```
➜  google-blockly-games git:(master) ✗ make puzzle-en
java -jar third-party-downloads/SoyToJsSrcCompiler.jar --shouldProvideRequireSoyNamespaces --isUsingIjData --outputPathFormat appengine/generated/en/soy.js --srcs appengine/template.soy
java -jar third-party-downloads/SoyToJsSrcCompiler.jar --shouldProvideRequireSoyNamespaces --isUsingIjData --outputPathFormat appengine/puzzle/generated/en/soy.js --srcs appengine/puzzle/template.soy
python2 build-app.py puzzle en
Scanning for Blockly messages in puzzle...
Compressed to 250 KB.
Found 33 Blockly messages.
Compiling Puzzle - en
third-party-downloads/build/closurebuilder.py: Scanning paths...
Traceback (most recent call last):
  File "third-party-downloads/build/closurebuilder.py", line 300, in <module>
    main()
  File "third-party-downloads/build/closurebuilder.py", line 224, in main
    if js_path not in options.excludes:
TypeError: argument of type 'NoneType' is not iterable
Found 0 dependencies.
Compressed to 251 KB.


```

**Comment by Seransei** [comment]
Hi, 

I ran accross the exact same problem which blocks me a lot in my work. 

I described it in #201 a few days ago.

If you or anyone happens to solve this problem I'd be glad to hear about it.

Thank you.

**Comment by Sachin5411** [comment]
@Seransei
 Thanks for the solution , it worked for me :)

**Comment by NeilFraser** [comment]
Lovely, the Closure Compiler team made a change that requires '--exclude' be used, even if it is empty.
Fixed via https://github.com/google/blockly-games/commit/530c6926ed7baf662ad845350ef8b4344e6f482f

Thanks for the report.
