### ISSUE TITLE
make en >> not working

### ISSUE THREAD

**Issue by PracticalCode** [google/blockly-games#208]
I was able to **`make deps`**; however, I did have to make an alteration to the **`Makefile`** ...
```
150-:	wget -N https://dl.google.com/closure-compiler/compiler-latest.zip; \
150+:	wget -N https://dl.google.com/closure-compiler/compiler-20200719.zip; \
151+:	mv compiler-20200719.zip compiler-latest.zip; \
```

I was going to create a PR for this, but after I ensured everything worked (which was unfortunately not the case).

Here are some of the **`make en`** errors (actually, it's the same error that repeats over & over) ...

```
sudo make en
mkdir -p appengine/generated/en/
java -jar third-party-downloads/SoyToJsSrcCompiler.jar --shouldProvideRequireSoyNamespaces --isUsingIjData --outputPathFormat appengine/index/generated/en/soy.js --srcs appengine/index/template.soy
python build-app.py index en
Scanning for Blockly messages in index...
Compressed to 8 KB.
Found 0 Blockly messages.
Compiling Index - en
third-party-downloads/build/closurebuilder.py: Scanning paths...
**_Traceback (most recent call last):
  File "third-party-downloads/build/closurebuilder.py", line 300, in <module>
    main()
  File "third-party-downloads/build/closurebuilder.py", line 224, in main
    if js_path not in options.excludes:
TypeError: argument of type 'NoneType' is not iterable_**
Found 0 dependencies.
Compressed to 8 KB.

java -jar third-party-downloads/SoyToJsSrcCompiler.jar --shouldProvideRequireSoyNamespaces --isUsingIjData --outputPathFormat appengine/generated/en/soy.js --srcs appengine/template.soy
java -jar third-party-downloads/SoyToJsSrcCompiler.jar --shouldProvideRequireSoyNamespaces --isUsingIjData --outputPathFormat appengine/puzzle/generated/en/soy.js --srcs appengine/puzzle/template.soy
python build-app.py puzzle en
Scanning for Blockly messages in puzzle...
Compressed to 256 KB.
Found 33 Blockly messages.
Compiling Puzzle - en
third-party-downloads/build/closurebuilder.py: Scanning paths...
Traceback (most recent call last):
  File "third-party-downloads/build/closurebuilder.py", line 300, in <module>
    main()
  File "third-party-downloads/build/closurebuilder.py", line 224, in main
    if js_path not in options.excludes:
TypeError: argument of type 'NoneType' is not iterable
Found 0 dependencies.
Compressed to 258 KB.

java -jar third-party-downloads/SoyToJsSrcCompiler.jar --shouldProvideRequireSoyNamespaces --isUsingIjData --outputPathFormat appengine/maze/generated/en/soy.js --srcs appengine/maze/template.soy
python build-app.py maze en
Scanning for Blockly messages in maze...
Compressed to 294 KB.
Found 33 Blockly messages.
Compiling Maze - en
third-party-downloads/build/closurebuilder.py: Scanning paths...
Traceback (most recent call last):
  File "third-party-downloads/build/closurebuilder.py", line 300, in <module>
    main()
  File "third-party-downloads/build/closurebuilder.py", line 224, in main
    if js_path not in options.excludes:
TypeError: argument of type 'NoneType' is not iterable
Found 0 dependencies.
Compressed to 0 KB.

etc... etc... etc... etc... etc... >>>
```

Relevant Code Snippets from **`closurebuilder.py`** :
```
221:  logging.info('Scanning paths...')
222:  for path in options.roots:
223:    for js_path in treescan.ScanTreeForJsFiles(path):
224:      if js_path not in options.excludes:
225:        sources.add(_PathSource(js_path))
... ... ...    ... ... ... 
295:if __name__ == '__main__':
296:  main()
```

System Info:
Ubuntu 20.04.1 LTS

Python Info:
Python 2.7.18rc1

Java Info:
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-0ubuntu2~20.04-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)

**Comment by NeilFraser** [comment]
These issues were all resolved on 16 Sep 2020.  Have you tried pulling from the repo?
