### ISSUE TITLE
make languages fail

### ISSUE THREAD

**Issue by suiato** [google/blockly-games#219]
"make languages" failed. (Ubuntu 20.04 server on Linode, forked) "make deps" and "make en" worked.

> suiato@localhost:~/git/blockly-games$ make languages
> Converting Soy files to JSON for Translatewiki.
> java -jar third-party-downloads/SoyMsgExtractor.jar --outputFile extracted_msgs.xlf --srcs appengine/template.soy,appengine/index/template.soy,appengine/puzzle/template.soy,appengine/maze/template.soy,appengine/bird/template.soy,appengine/turtle/template.soy,appengine/movie/template.soy,appengine/music/template.soy,appengine/pond/docs/template.soy,appengine/pond/template.soy,appengine/pond/tutor/template.soy,appengine/pond/duck/template.soy,appengine/gallery/template.soy
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$2 (file:/home/suiato/git/blockly-games/third-party-downloads/SoyMsgExtractor.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
> WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$2
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> i18n/xliff_to_json.py --xlf extracted_msgs.xlf --templates appengine/template.soy,appengine/index/template.soy,appengine/puzzle/template.soy,appengine/maze/template.soy,appengine/bird/template.soy,appengine/turtle/template.soy,appengine/movie/template.soy,appengine/music/template.soy,appengine/pond/docs/template.soy,appengine/pond/template.soy,appengine/pond/tutor/template.soy,appengine/pond/duck/template.soy,appengine/gallery/template.soy
> Created file: ./json/en.json
> Created file: ./json/qqq.json
> Created file: ./json/keys.json
> Removed extracted_msgs.xlf
> 
> Generating JS from appengine/{./,index,puzzle,maze,bird,turtle,movie,music,pond/docs,pond,pond/tutor,pond/duck,gallery}/template.soy
> Creating .xlf files...
> Creating .js files...
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$2 (file:/home/suiato/git/blockly-games/third-party-downloads/SoyToJsSrcCompiler.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
> WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$2
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> Exception in thread "main" com.google.template.soy.base.SoySyntaxException: Error opening Soy file appengine/{.: java.io.FileNotFoundException: appengine/{. (Is a directory)
>         at com.google.template.soy.base.SoySyntaxException.createWithoutMetaInfo(SoySyntaxException.java:52)
>         at com.google.template.soy.soyparse.SoyFileSetParser.parseSoyFileHelper(SoyFileSetParser.java:261)
>         at com.google.template.soy.soyparse.SoyFileSetParser.parseWithVersions(SoyFileSetParser.java:213)
>         at com.google.template.soy.soyparse.SoyFileSetParser.parse(SoyFileSetParser.java:173)
>         at com.google.template.soy.SoyFileSet.compileToJsSrcFiles(SoyFileSet.java:921)
>         at com.google.template.soy.SoyToJsSrcCompiler.execMain(SoyToJsSrcCompiler.java:307)
>         at com.google.template.soy.SoyToJsSrcCompiler.main(SoyToJsSrcCompiler.java:243)
> Traceback (most recent call last):
>   File "i18n/json_to_js.py", line 253, in <module>
>     main()
>   File "i18n/json_to_js.py", line 241, in main
>     '--srcs', args.template])
>   File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['java', '-jar', 'third-party-downloads/SoyToJsSrcCompiler.jar', '--locales', 'ab,ace,af,am,ar,arz,ast,az,ba,be-tarask,be,bg,bn,br,ca,cdo,cs,da,de,diq,el,en,eo,es,et,eu,fa,fi,fo,fr,frr,gl,gn,ha,hak,he,hi,hrx,hu,hy,ia,id,ig,inh,is,it,ja,ka,kab,kbd-cyrl,km,kn,ko,ksh,ku-latn,ky,la,lb,lki,lrc,lt,lv,mg,mk,ml,mr,ms,my,mzn,nb,ne,nl,oc,olo,pa,pl,pms,ps,pt-br,pt,ro,ru,sc,sco,sd,si,sk,skr-arab,sl,sq,sr-latn,sr,sv,sw,ta,tcy,te,th,ti,tr,uk,ur,vi,yo,zh-hans,zh-hant', '--shouldProvideRequireSoyNamespaces', '--isUsingIjData', '--messageFilePathFormat', 'appengine/{./,index,puzzle,maze,bird,turtle,movie,music,pond/docs,pond,pond/tutor,pond/duck,gallery}/generated/{LOCALE}.xlf', '--outputPathFormat', 'appengine/{./,index,puzzle,maze,bird,turtle,movie,music,pond/docs,pond,pond/tutor,pond/duck,gallery}/generated/{LOCALE}/soy.js', '--srcs', 'appengine/{./,index,puzzle,maze,bird,turtle,movie,music,pond/docs,pond,pond/tutor,pond/duck,gallery}/template.soy']' returned non-zero exit status 1
> 
> Scanning for Blockly messages in {index,puzzle,maze,bird,turtle,movie,music,pond/docs,pond/tutor,pond/duck,gallery}...
> Traceback (most recent call last):
>   File "build-app.py", line 289, in <module>
>     main(sys.argv[1], None)
>   File "build-app.py", line 58, in main
>     filterMessages(name, langs[0])
>   File "build-app.py", line 67, in filterMessages
>     f = open('appengine/%s/generated/%s/msg.js' % (name, lang), 'w')
> IOError: [Errno 2] No such file or directory: u'appengine/{index,puzzle,maze,bird,turtle,movie,music,pond/docs,pond/tutor,pond/duck,gallery}/generated/ar/msg.js'
> make: *** [Makefile:130: languages] Error 1

**Comment by suiato** [comment]
While "make languages" failed, "make index" etc. worked.

**Comment by JEZIGA01** [comment]
You must have all packages installed! 
If you are on Win, open PowerShell as ADM and paste this command to install wsl: 
command: wsl --install 
doc: https://docs.microsoft.com/en-us/windows/wsl/install

Enter a password and login, restart your computer.

Type wsl to open the terminal on your Win, go to the blockly-games directory and type the commands:

sudo apt update

sudo apt-get install subversion 
sudo apt-get install sed
sudo apt-get install wget 
sudo apt-get install make 
sudo apt install default-jre
sudo apt install default-jdk
sudo apt-get install software-properties-common
sudo apt-get install python3

And finally type the make command in the root of your project (blockly-games) where the MakeFile is and watch the magic happen, hehe.
