### ISSUE TITLE
Building language fails

### ISSUE THREAD

**Issue by LabCity** [google/blockly-games#28]
Hi all,

So I have successfully made the dependencies. However, when I try to make pond tutor (or anyother game) in english, I get the following error:

closure-library-bin-read-only/build/closurebuilder.py: Compiling with the following command: java -d32 -client -jar closure-compiler-read-only/build/compiler.jar --flagfile /tmp/tmprKORHT
ERROR - /tmp/tmprKORHT read error.
Sample usage: --compilation_level (-O) VAL --externs VAL --js VAL --js_output_file VAL --warning_level (-W) [QUIET | DEFAULT | VERBOSE]
Run with --help for all options and details
Traceback (most recent call last):
  File "closure-library-bin-read-only/build/closurebuilder.py", line 293, in <module>
    main()
  File "closure-library-bin-read-only/build/closurebuilder.py", line 282, in main
    compiler_flags=options.compiler_flags)
  File "/cygdrive/c/Users/hardi/OneDrive/Documents/GitHub/blockly-games/closure-library-bin-read-only/build/jscompiler.py", line 160, in Compile
    raise JsCompilerError('JavaScript compilation failed.')
jscompiler.JsCompilerError: JavaScript compilation failed.

Any help would be greatly appreciated. Thank you very much.

**Comment by NeilFraser** [comment]
I can confirm that the build is working properly for me.  Looks like your system is having problems reading the flag file in the /tmp directory.

For reference, this is what I see on OS X:

```
closure-library-bin-read-only/build/closurebuilder.py: Compiling with the following command: java -client -jar closure-compiler-read-only/build/compiler.jar --flagfile /var/folders/2w/qbwbtmcn7lv_qc6p7v4xj6dw00189n/T/tmp_zUPKR
closure-library-bin-read-only/build/closurebuilder.py: JavaScript compilation succeeded.
```

Looking at the tmp_zUPKR file (which disappears as soon as the compile completes) gives me a list of JS files to compile:
```
--js appengine/js-read-only/goog/base.js --js appengine/js-read-only/goog/string/stringbuffer.js --js appengine/js-read-only/goog/dom/nodetype.js --js appengine/js-read-only/goog/debug/error.js --js appengine/js-read-only/goog/string/string.js --js appengine/js-read-only/goog/asserts/asserts.js [..and lots more...]
```

Hope this gives some hints for what's wrong on your end.  Sorry that the issue is not immediately obvious to me.

**Comment by carlosperate** [comment]
Looks like you are trying to build using Cygwin under windows. Have you tried running the script under the windows command line?

**Comment by LabCity** [comment]
Hey Carlos,

Thanks for your input (thank you Neil as well). When I try to compile in windows using the mingw make command. I get the following error:

`Pond/Tutor - en - uncompressed:
Traceback (most recent call last):
  File "build-app.py", line 215, in <module>
    main(sys.argv[1], sys.argv[2])
  File "build-app.py", line 93, in main
    write_uncompressed(name, lang)
  File "build-app.py", line 110, in write_uncompressed
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE)
  File "C:\Users\hardi\Anaconda2\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Users\hardi\Anaconda2\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 193] %1 is not a valid Win32 application
Makefile:52: recipe for target 'pond-tutor-en' failed
mingw32-make: *** [pond-tutor-en] Error 1`

Seems to be something to do with my python. I checked Anaconda which is a python distribution is in my system Path as well as Anaconda/Scripts. Thanks for your help!

**Comment by JonathanHalim** [comment]
I got the same error too, is there any soluton for this error?

**Comment by tonygao2k** [comment]
Same error exists on my side, i'm using Cygwin under windows.

**Comment by luthijm** [comment]
Hello,
I have an error when buiding language:
make languages
java -jar third-party/SoyMsgExtractor.jar --outputFile extracted_msgs.xlf --srcs appengine/template.soy,appengine/index/template.soy,appengine/puzzle/template.soy,appengine/maze/template.soy,appengine/bird/template.soy,appengine/turtle/template.soy,appengine/movie/template.soy,appengine/pond/docs/template.soy,appengine/pond/template.soy,appengine/pond/tutor/template.soy,appengine/pond/duck/template.soy
i18n/xliff_to_json.py --xlf extracted_msgs.xlf --templates appengine/template.soy,appengine/index/template.soy,appengine/puzzle/template.soy,appengine/maze/template.soy,appengine/bird/template.soy,appengine/turtle/template.soy,appengine/movie/template.soy,appengine/pond/docs/template.soy,appengine/pond/template.soy,appengine/pond/tutor/template.soy,appengine/pond/duck/template.soy
Created file: ./json/en.json
Created file: ./json/qqq.json
Created file: ./json/keys.json
Removed extracted_msgs.xlf
Creating .xlf files...
Creating .js files...
Exception in thread "main" com.google.template.soy.base.SoySyntaxException: Error opening Soy file appengine/{.: java.io.FileNotFoundException: appengine/{. (est un dossier)
	at com.google.template.soy.base.SoySyntaxException.createWithoutMetaInfo(SoySyntaxException.java:52)
	at com.google.template.soy.soyparse.SoyFileSetParser.parseSoyFileHelper(SoyFileSetParser.java:261)
	at com.google.template.soy.soyparse.SoyFileSetParser.parseWithVersions(SoyFileSetParser.java:213)
	at com.google.template.soy.soyparse.SoyFileSetParser.parse(SoyFileSetParser.java:173)
	at com.google.template.soy.SoyFileSet.compileToJsSrcFiles(SoyFileSet.java:921)
	at com.google.template.soy.SoyToJsSrcCompiler.execMain(SoyToJsSrcCompiler.java:307)
	at com.google.template.soy.SoyToJsSrcCompiler.main(SoyToJsSrcCompiler.java:243)
Traceback (most recent call last):
  File "i18n/json_to_js.py", line 252, in <module>
    main()
  File "i18n/json_to_js.py", line 239, in main
    '--srcs', args.template])
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['java', '-jar', 'third-party/SoyToJsSrcCompiler.jar', '--locales', 'ab,ace,af,ar,arz,ast,az,ba,be-tarask,be,bg,bn,br,ca,cdo,cs,da,de,diq,el,en,eo,es,et,eu,fa,fi,fo,fr,frr,gl,gn,hak,he,hi,hrx,hu,ia,id,is,it,ja,ka,kab,kbd-cyrl,km,ko,ksh,ku-latn,ky,la,lb,lki,lrc,lt,lv,mg,mk,ml,mr,ms,my,mzn,nb,ne,nl,oc,pa,pl,pms,ps,pt-br,pt,ro,ru,sc,sco,sd,si,sk,sl,sr,sv,sw,ta,tcy,te,th,tr,uk,vi,zh-hans,zh-hant', '--shouldProvideRequireSoyNamespaces', '--isUsingIjData', '--messageFilePathFormat', 'appengine/{./,index,puzzle,maze,bird,turtle,movie,pond/docs,pond,pond/tutor,pond/duck}/generated/{LOCALE}.xlf', '--outputPathFormat', 'appengine/{./,index,puzzle,maze,bird,turtle,movie,pond/docs,pond,pond/tutor,pond/duck}/generated/{LOCALE}/soy.js', '--srcs', 'appengine/{./,index,puzzle,maze,bird,turtle,movie,pond/docs,pond,pond/tutor,pond/duck}/template.soy']' returned non-zero exit status 1
Makefile:70 : la recette pour la cible « languages » a échouée
make: *** [languages] Erreur 1

What can I dot?
Iam under Linux mint 18.2 cinnamon 64-bit
thanks for your help
