### ISSUE TITLE
ImportError: No module named jscompiler

### ISSUE THREAD

**Issue by acekingke** [google/blockly-games#46]
## When I build movie-en It has occur error
Movie - en - uncompressed:
Traceback (most recent call last):
  File "third-party/build/closurebuilder.py", line 39, in <module>
    import jscompiler
ImportError: No module named jscompiler

Movie - en - compressed:
Traceback (most recent call last):
  File "third-party/build/closurebuilder.py", line 39, in <module>
    import jscompiler
ImportError: No module named jscompiler

**Comment by NeilFraser** [comment]
Did you 'make deps' first?

**Comment by acekingke** [comment]
Yes, I resolve the problem by pip install https://github.com/jeffkistler/jscompiler/archive/master.zip
