### ISSUE TITLE
make maze-en Error

### ISSUE THREAD

**Issue by acekingke** [google/blockly-games#47]
## When I make maze-en , It occurr the problem
➜  blockly-games-master make maze-en
java -jar third-party/SoyToJsSrcCompiler.jar --shouldProvideRequireSoyNamespaces --isUsingIjData --outputPathFormat appengine/generated/en/soy.js --srcs appengine/template.soy
java -jar third-party/SoyToJsSrcCompiler.jar --shouldProvideRequireSoyNamespaces --isUsingIjData --outputPathFormat appengine/maze/generated/en/soy.js --srcs appengine/maze/template.soy
python build-app.py maze en

Maze - en - uncompressed:
Traceback (most recent call last):
  File "third-party/build/closurebuilder.py", line 40, in <module>
    import source
ImportError: No module named source

Maze - en - compressed:
Traceback (most recent call last):
  File "third-party/build/closurebuilder.py", line 40, in <module>
    import source
ImportError: No module named source
➜  blockly-games-master

**Comment by acekingke** [comment]
delete the build directory , and the make deps again , then problem is resolved, Thanks
