### ISSUE TITLE
make maze-en fails

### ISSUE THREAD

**Issue by Dlearn** [google/blockly-games#51]
Hi all,

I think I have `make deps` successfully, but when I `make maze-en`, I run into a strange error.

(I am currently using jdk1.7 because of Issue #21)
(jdk1.8 previously had a similar error)

```
make maze-en
java -jar third-party/SoyToJsSrcCompiler.jar --shouldProvideRequireSoyNamespaces --isUsingIjData --outputPathFormat appengine/generated/en/soy.js --srcs appengine/template.soy
java -jar third-party/SoyToJsSrcCompiler.jar --shouldProvideRequireSoyNamespaces --isUsingIjData --outputPathFormat appengine/maze/generated/en/soy.js --srcs appengine/maze/template.soy
python build-app.py maze en

Maze - en - uncompressed:
third-party/build/closurebuilder.py: Scanning paths...
third-party/build/closurebuilder.py: 2241 sources scanned.
third-party/build/closurebuilder.py: Building dependency tree..

Maze - en - compressed:
third-party/build/closurebuilder.py: Scanning paths...
third-party/build/closurebuilder.py: 2241 sources scanned.
third-party/build/closurebuilder.py: Building dependency tree..
third-party/build/closurebuilder.py: Closure Compiler now natively understands and orders Closure dependencies and
is prefererred over using this script for performing JavaScript compilation.

Please migrate your codebase.

See:
https://github.com/google/closure-compiler/wiki/Managing-Dependencies

third-party/build/closurebuilder.py: Compiling with the following command: java -client -jar third-party/closure-compiler.jar --flagfile /var/folders/nz/_cdyftyx577ff3rh6k1z0rs40000gn/T/tmps7UlJG
appengine/js/lib-dialogs.js:90: WARNING - Access to private property bindEvent_ of Blockly not allowed here.
        Blockly.bindEvent_(header, 'mousedown', null,
        ^^^^^^^^^^^^^^^^^^

appengine/js/lib-dialogs.js:142: WARNING - Access to private property bindEvent_ of Blockly not allowed here.
  BlocklyDialogs.dialogMouseUpWrapper_ = Blockly.bindEvent_(document,
                                         ^^^^^^^^^^^^^^^^^^

appengine/js/lib-dialogs.js:144: WARNING - Access to private property bindEvent_ of Blockly not allowed here.
  BlocklyDialogs.dialogMouseMoveWrapper_ = Blockly.bindEvent_(document,
                                           ^^^^^^^^^^^^^^^^^^

appengine/js/lib-dialogs.js:173: WARNING - Access to private property unbindEvent_ of Blockly not allowed here.
    Blockly.unbindEvent_(BlocklyDialogs.dialogMouseUpWrapper_);
    ^^^^^^^^^^^^^^^^^^^^

appengine/js/lib-dialogs.js:177: WARNING - Access to private property unbindEvent_ of Blockly not allowed here.
    Blockly.unbindEvent_(BlocklyDialogs.dialogMouseMoveWrapper_);
    ^^^^^^^^^^^^^^^^^^^^




/ ************************************************************************* /
/ *                               … …                                     * /
/ *                      LOTS OF OTHER WARNINGS                           * /
/ *                               … …                                     * /
/ ************************************************************************* /




externs/interpreter-externs.js:114: WARNING - Bad type annotation. Unknown type Interpreter.Primitive
 * @return {!Interpreter.Object|!Interpreter.Primitive} The equivalent
                                 ^

externs/interpreter-externs.js:122: WARNING - Bad type annotation. Unknown type Interpreter.Object
 * @param {!Interpreter.Object} pseudoObj The JS interpreter object to be
            ^

externs/svg-externs.js:407: WARNING - mismatch of the addEventListener property type and the type of the property it overrides from interface EventTarget
original: function (this:EventTarget, string, (EventListener|function (Event): (boolean|undefined)|null), boolean): undefined
override: function (this:SVGElementInstance, string, (EventListener|function ((Event|null)): (boolean|undefined)|null), boolean=): undefined
SVGElementInstance.prototype.addEventListener = function(type, listener, opt_useCapture){};
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

externs/svg-externs.js:415: WARNING - mismatch of the removeEventListener property type and the type of the property it overrides from interface EventTarget
original: function (this:EventTarget, string, (EventListener|function (Event): (boolean|undefined)|null), boolean): undefined
override: function (this:SVGElementInstance, string, (EventListener|function ((Event|null)): (boolean|undefined)|null), boolean=): undefined
SVGElementInstance.prototype.removeEventListener = function(type, listener, opt_useCapture){};
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

appengine/third-party/blockly/core/workspace.js:321: ERROR - functions can only be declared at top level or immediately within another function in ES5 strict mode
    function doDeletion() {
    ^^^^^^^^^^^^^^^^^^^^^^^

1 error(s), 794 warning(s), 96.4% typed
Traceback (most recent call last):
  File "third-party/build/closurebuilder.py", line 293, in <module>
    main()
  File "third-party/build/closurebuilder.py", line 282, in main
    compiler_flags=options.compiler_flags)
  File "/Users/codegakko/blockly-games/third-party/build/jscompiler.py", line 160, in Compile
    raise JsCompilerError('JavaScript compilation failed.')
jscompiler.JsCompilerError: JavaScript compilation failed.
```

Can anyone make sense of this? Any help would be greatly appreciated. Thank you very much.

**Comment by saranshcurieo** [comment]
running into the same problem .. have you found the solution ??

**Comment by Dlearn** [comment]
No, sorry. I'm going to close this because it's really old.
