### ISSUE TITLE
make en

### ISSUE THREAD

**Issue by zeroPlushyl** [google/blockly-games#54]
1 error(s), 1 warning(s)
Traceback (most recent call last):
  File "third-party/build/closurebuilder.py", line 293, in <module>
    main()
  File "third-party/build/closurebuilder.py", line 282, in main
    compiler_flags=options.compiler_flags)
  File "/home/zero/Documents/blockly/blockly-games/third-party/build/jscompiler.py", line 160, in Compile
    raise JsCompilerError('JavaScript compilation failed.')
jscompiler.JsCompilerError: JavaScript compilation failed.

**Comment by NeilFraser** [comment]
Several dependencies (including Blockly) changed over time, breaking the build.  Blockly Games has been updated so that everything builds properly now.
