### ISSUE TITLE
%1 is not a valid Win32 application 

### ISSUE THREAD

**Issue by ChristosPatsalis** [google/blockly-games#82]
Hi,
When I try to build english version of the game with make en, i get this error:

$ make en
mkdir -p appengine/generated/en/
java -jar third-party/SoyToJsSrcCompiler.jar --shouldProvideRequireSoyNamespaces --isUsingIjData --outputPathFormat appengine/index/generated/en/soy.js --srcs appengine/index/template.soy
python build-app.py index en

Index - en - uncompressed:
Traceback (most recent call last):
  File "build-app.py", line 89, in write_uncompressed
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE)
  File "C:\Users\Christos Patsalis\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Christos Patsalis\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build-app.py", line 214, in <module>
    main(sys.argv[1], sys.argv[2])
  File "build-app.py", line 42, in main
    language(name, lang)
  File "build-app.py", line 71, in language
    write_uncompressed(name, lang)
  File "build-app.py", line 91, in write_uncompressed
    print("Failed to Popen: %s" & cmd)
TypeError: unsupported operand type(s) for &: 'str' and 'list'
make: *** [Makefile:22: index-en] Error 1

Any idea what might be the problem and how to fix it?

**Comment by NeilFraser** [comment]
Sorry, I can't help with Windows errors.  Those machines are very hard to come by at Google.  Here's a photo from several years ago where I did manage to get my hands on one:

![windows](https://user-images.githubusercontent.com/250480/40812392-764fb9e2-64ea-11e8-964d-967a92f45917.jpg)

If you do figure out a solution, we accept Pull Requests as long as it doesn't break Linux/OSX.
